### PR TITLE
[OID4VP] Fix unsupportedClientIdScheme error with x509_san_dns client ID formatting

### LINKED ISSUE #44: [OID4VP] Fix unsupportedClientIdScheme error by properly formatting client ID with x509_san_dns scheme
Wallet receives "unsupportedClientIdScheme" error because client ID in OpenID4VP authorization request URL is not prefixed with the required scheme. The wallet expects "x509_san_dns:clientId" format but receives plain "clientId", causing it to default to preRegistered scheme.

### PR DESCRIPTION
**Pull request by Awambeng**
This PR fixes an issue where the wallet rejects OpenID4VP authorization requests due to an invalid client ID scheme.

**Key changes**
- Prefixed client_id with x509_san_dns: in authorization request URLs
- Ensured wallet correctly recognizes and validates the client ID scheme
- Added test to verify correct client ID formatting
- Validated proper URL encoding/decoding in tests

Closes #44

### CODE REVIEW

File: src/test/java/io/github/adorsysgis/keycloak/protocol/oid4vc/oid4vp/OID4VPUserAuthEndpointTest.java [hunk 1]
```diff
@@ -816,7 +854,8 @@ public void shouldAuthenticateSuccessfully_InOIDCFlow() throws Exception {
             assertNotEquals("New code must be issued", authCode, freshAuthCode);
 
             // TODO: A login method param must be appended to the redirect URI
-            // String loginMethod = uriInfo.getQueryParameters().getFirst(PARAM_LOGIN_METHOD);
+            // String loginMethod =
+            // uriInfo.getQueryParameters().getFirst(PARAM_LOGIN_METHOD);
             // assertEquals(OID4VP_AUTH_LOGIN_PATH, loginMethod);
         }
```
Comment (IngridPuppet) [inline src/test/java/io/github/adorsysgis/keycloak/protocol/oid4vc/oid4vp/OID4VPUserAuthEndpointTest.java:841]: Could you configure your formatter not to wrap these comments?

File: src/test/java/io/github/adorsysgis/keycloak/protocol/oid4vc/oid4vp/OID4VPUserAuthEndpointTest.java [hunk 2]
```diff
@@ -85,6 +89,32 @@ public void shouldProduceAuthorizationRequests() throws Exception {
...
+        URI authRequest = new URI(authContext.getAuthorizationRequest());
+        String query = authRequest.getQuery();
+
+        assertNotNull(query, "Authorization request query should not be null");
+
+        // Parse query parameters into a map
+        Map<String, String> params = Arrays.stream(query.split("&"))
+                .map(param -> param.split("=", 2))
+                .filter(pair -> pair.length == 2)
+                .collect(Collectors.toMap(pair -> pair[0], pair -> pair[1]));
```
Comment (IngridPuppet) [inline src/test/java/io/github/adorsysgis/keycloak/protocol/oid4vc/oid4vp/OID4VPUserAuthEndpointTest.java]: There is a getQueryParameters or similar for this logic.

**Review by IngridPuppet — COMMENTED** [review]
Let's reduce noise...

**Review by IngridPuppet — APPROVED** [review]
LGTM. Please squash when merging.
